# Rdio Scanner System ID
systemId: 1
# Rdio Scanner API Key
apiKey: 1
# Rdio Scanner End Point
endPoint: http://localhost:3000

# Master connection information
master:
    # Address of the master
    address: 127.0.0.1
    # Port of the master
    port: 3000
    # Auth key
    authKey: "UNAUTH"
    # Radio Id used to send a fake affiliation to tell the master to route us audio
    radioId: 127600
    # Register as a conventional peer to the master to skip the need for affiliations. (NOTE: This tells the master to route everything to us)
    convPeerMode: false
    # Delete audio files when done with them
    deleteDoneFiles: true

# List of talkgroups to receive
talkgroups:
    - 2001
    - 2002
    - 1001
    - 1002